# Generated by Django 5.0.6 on 2024-06-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_review_text_review_body_project_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='kind_of_job',
            field=models.IntegerField(choices=[(0, 'Практика'), (1, 'Стажировка'), (2, 'Вакансия')], default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=1),
        ),
    ]
