# Generated by Django 5.0.6 on 2024-06-08 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_city'),
        ('users', '0007_alter_profile_middle_name_alter_profile_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='specialnost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.special'),
        ),
    ]
